Repository top-developers-group/words, pull requests merged in 2022-02, with the labels that each got.

#2 Create lit
  lit
Labels: ok i think

#3 pickle
  pickle
Labels: ok i think

#8 dragon
  dragon
Labels: ok i think

#10 Create vaporeon
  .gitignore
  vaporeon
Labels: this is a pr

#9 Create key
  key
Labels: this is a pr

#11 Create test
  test
Labels: ok i think, this is a pr

#12 Create piano
  piano
Labels: ok i think, this is a pr

#18 Create wyoming
  wyoming
Labels: ok i think, this is a pr, actually very pog, word

#19 Create unibrow
  unibrow
Labels: ok i think, this is a pr, actually very pog, word

#20 Create green
  green
Labels: ok i think, this is a pr, actually very pog, word
